create table book (
book_id bigint generated by default as identity, 
author varchar(50) not null, 
book_name varchar(100) not null, 
category varchar(50) not null, 
description varchar(200) not null, 
publish_year integer not null, 
primary key (book_id),
unique key UK_bookname (book_name)
)
